name: Build Release Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - release

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: jgarden

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare build files
        run: cp Dockerfile target

      - name: Log into registry
        run: docker login hub.aidong-ai.com --username zzw --password Aidong@2020

      - name: Build image
        run: |
          pushd target
          docker build -t hub.aidong-ai.com/aidong/jgarden:latest .
          popd

      - name: Push image
        run: |
          docker push hub.aidong-ai.com/aidong/jgarden:latest
